[package]
name = "mycroft"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
surrealdb = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }